export const OPEN_TAG_MODAL = "OPEN_TAG_MODAL";
export const CLOSE_TAG_MODAL = "CLOSE_TAG_MODAL";
export const OPEN_CREATE_POST_MODAL = "OPEN_CREATE_POST_MODAL";
export const CLOSE_CREATE_POST_MODAL = "CLOSE_CREATE_POST_MODAL";