//initiative action types
export const CREATE_INITIATIVE = 'CREATE_INITIATIVE';
export const RETRIEVE_INITIATIVES = 'RETRIEVE_INITIATIVES';
export const SELECT_INITIATIVE = 'SELECT_INITIATIVE';
export const DELETE_INITIATIVE = 'DELETE_INITIATIVE';
export const EDIT_INITIATIVE = 'EDIT_INITIATIVE';

//requirement action types
export const CREATE_REQUIREMENT = 'CREATE_REQUIREMENT';
export const GET_REQUIREMENT = 'GET_REQUIREMENT';
export const DELETE_REQUIREMENT = 'DELETE_REQUIREMENT';
export const EDIT_REQUIREMENT = 'EDIT_REQUIREMENT';
export const SELECT_REQUIREMENT = 'SELECT_REQUIREMENT';
export const ADD_REQUIREMENT_VISIBILITY = 'ADD_REQUIREMENT_VISIBILITY';
export const REMOVE_REQUIREMENT_VISIBILITY = 'REMOVE_REQUIREMENT_VISIBILITY';
export const ADD_REQUIREMENT_TAG = 'ADD_REQUIREMENT_TAG';
export const DELETE_REQUIREMENT_TAG = 'DELETE_REQUIREMENT_TAG';
export const ADD_REQUIREMENT_ASSIGNMENT = 'ADD_REQUIREMENT_ASSIGNMENT';
export const DELETE_REQUIREMENT_ASSIGNMENT = 'DELETE_REQUIREMENT_ASSIGNMENT';
export const CREATE_REQUIREMENT_CUSTOMFIELD = 'CREATE_REQUIREMENT_CUSTOMFIELD';
export const DELETE_REQUIREMENT_CUSTOMFIELD = 'DELETE_REQUIREMENT_CUSTOMFIELD';
export const RETRIEVE_REQUIREMENTS = 'RETRIEVE_REQUIREMENTS';

//roadmap action types
export const CREATE_ROADMAP = 'CREATE_ROADMAP';
export const SELECT_PRODUCT_ROADMAP = 'SELECT_PRODUCT_ROADMAP';
export const GET_ROADMAP = 'GET_ROADMAP';
export const DELETE_ROADMAP = 'DELETE_ROADMAP';
export const EDIT_ROADMAP = 'EDIT_ROADMAP';

//timeblock action types
export const CREATE_TIMEBLOCK = 'CREATE_TIMEBLOCK';
export const GET_TIMEBLOCK = 'GET_TIMEBLOCK';
export const DELETE_TIMEBLOCK = 'DELETE_TIMEBLOCK';
export const EDIT_TIMEBLOCK = 'EDIT_TIMEBLOCK';
export const SELECT_TIMEBLOCK = 'SELECT_TIMEBLOCK';